# Generated by Django 2.2.1 on 2019-06-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190601_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
        migrations.AddField(
            model_name='like',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
